name: colegio_app
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.8
  table_calendar: ^3.0.9
  flutter_local_notifications: ^16.3.0
  connectivity_plus: ^5.0.0
  sqflite: ^2.3.0
  path: ^1.8.3
  image_picker: ^1.0.0
  vibration: ^1.8.4
  path_provider: ^2.1.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
